server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - AuthenticationFilter

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - AuthenticationFilter

        - id: auth-open
          uri: lb://account-service
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: bmo-banking-secret-key-2023-very-long-secure

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
