server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:noreply@bmo.com}
    password: ${MAIL_PASSWORD:changeme}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  sqs:
    queue-name: bmo-notification-queue
    region: us-east-1
