server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmo_payments?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  sqs:
    queue-name: bmo-notification-queue
    region: us-east-1

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
